"""Schemas module initialization"""
from app.schemas.user import (
    UserBase,
    UserCreate,
    UserUpdate,
    UserResponse,
    Token,
    TokenPayload,
    LoginRequest,
    PasswordChange,
    PasswordReset,
    PasswordResetRequest,
)
from app.schemas.network import (
    DeviceBase,
    DeviceCreate,
    DeviceUpdate,
    DeviceResponse,
    DeviceListResponse,
    AnomalyBase,
    AnomalyCreate,
    AnomalyUpdate,
    AnomalyResponse,
    AnomalyListResponse,
    TrafficStats,
    TrafficSummary,
    AlertBase,
    AlertCreate,
    AlertResponse,
    AlertListResponse,
    PredictionRequest,
    PredictionResponse,
    BatchPredictionRequest,
    BatchPredictionResponse,
    DashboardStats,
    NetworkTopology,
)

__all__ = [
    # User schemas
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserResponse",
    "Token",
    "TokenPayload",
    "LoginRequest",
    "PasswordChange",
    "PasswordReset",
    "PasswordResetRequest",
    # Network schemas
    "DeviceBase",
    "DeviceCreate",
    "DeviceUpdate",
    "DeviceResponse",
    "DeviceListResponse",
    "AnomalyBase",
    "AnomalyCreate",
    "AnomalyUpdate",
    "AnomalyResponse",
    "AnomalyListResponse",
    "TrafficStats",
    "TrafficSummary",
    "AlertBase",
    "AlertCreate",
    "AlertResponse",
    "AlertListResponse",
    "PredictionRequest",
    "PredictionResponse",
    "BatchPredictionRequest",
    "BatchPredictionResponse",
    "DashboardStats",
    "NetworkTopology",
]
